import { FurnitureCatalogItem } from '../types';

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
  // --- LIVING ROOM ---
  {
    id: 'sectional-l-sofa',
    modelType: 'sectional-l-sofa',
    name: 'Nordic L-Shape Sectional Sofa',
    category: 'living',
    description: 'Deep modular L-sectional with high-density foam cushions, tapered oak legs, and chaise lounge.',
    dimensions: { width: 2.8, depth: 1.8, height: 0.85 },
    defaultColor: '#e5e2dc', // Oatmeal Bouclé
    secondaryColor: '#3a2e25', // Wood legs
    colorOptions: ['#e5e2dc', '#3f444c', '#b08a60', '#3b4e43', '#8c7b6c', '#2c3539'],
    price: 2450,
  },
  {
    id: 'linear-couch-3seat',
    modelType: 'linear-couch-3seat',
    name: 'Linear 3-Seater Tailored Couch',
    category: 'living',
    description: 'Clean Scandinavian 3-seater sofa with piped tailored seams and cylindrical bolster cushions.',
    dimensions: { width: 2.2, depth: 0.95, height: 0.82 },
    defaultColor: '#d6cfc7',
    secondaryColor: '#2b231d',
    colorOptions: ['#d6cfc7', '#34383c', '#987d64', '#4a5b52', '#a65b4c'],
    price: 1680,
  },
  {
    id: 'lounge-armchair',
    modelType: 'lounge-armchair',
    name: 'Curved Shell Lounge Armchair',
    category: 'living',
    description: 'Ergonomic sculptured lounge chair with plush wrapped seat cushion and black powder-coated steel legs.',
    dimensions: { width: 0.88, depth: 0.85, height: 0.8 },
    defaultColor: '#b59a7a', // Camel Velvet
    secondaryColor: '#1a1a1a',
    colorOptions: ['#b59a7a', '#ece8e1', '#374151', '#31493b', '#8b3a2b'],
    price: 790,
  },
  {
    id: 'coffee-table-minimal',
    modelType: 'coffee-table-minimal',
    name: 'Sculptural Marble Coffee Table',
    category: 'living',
    description: 'Low-slung solid marble oval coffee table with fluted pedestal base and lower brass tier.',
    dimensions: { width: 1.3, depth: 0.7, height: 0.42 },
    defaultColor: '#f1f1ee', // Marble / stone
    secondaryColor: '#b89c66', // Brass
    colorOptions: ['#f1f1ee', '#262626', '#d4af37', '#8c6d48'],
    price: 920,
  },
  {
    id: 'media-credenza-tv',
    modelType: 'media-credenza-tv',
    name: 'Fluted Media Credenza & OLED TV',
    category: 'living',
    description: 'Low-profile walnut TV console with slatted sliding doors and floating 65-inch ultra-thin display.',
    dimensions: { width: 2.1, depth: 0.45, height: 1.45 },
    defaultColor: '#5c4033', // Walnut
    secondaryColor: '#111827', // TV Screen
    colorOptions: ['#5c4033', '#c8ab8d', '#1f2937', '#e5e7eb'],
    price: 2150,
  },
  {
    id: 'open-bookshelf',
    modelType: 'open-bookshelf',
    name: 'Architectural Open Bookshelf',
    category: 'living',
    description: 'Steel-framed open shelving unit with asymmetrical solid wood display cubbies and book sets.',
    dimensions: { width: 1.2, depth: 0.38, height: 2.0 },
    defaultColor: '#2b231d',
    secondaryColor: '#1f2937',
    colorOptions: ['#2b231d', '#c2a688', '#374151', '#f3f4f6'],
    price: 1120,
  },
  {
    id: 'arc-floor-lamp',
    modelType: 'arc-floor-lamp',
    name: 'Monumental Brass Arc Floor Lamp',
    category: 'living',
    description: 'Sweeping brushed brass cantilever arc lamp with solid Carrara marble disc foundation.',
    dimensions: { width: 1.6, depth: 0.45, height: 2.15 },
    defaultColor: '#c5a059', // Brushed Brass
    secondaryColor: '#f3f4f6', // Marble base
    colorOptions: ['#c5a059', '#1f2937', '#9ca3af', '#dfd0b5'],
    price: 640,
  },
  {
    id: 'area-rug-woven',
    modelType: 'area-rug-woven',
    name: 'Artisan Textured Area Rug',
    category: 'living',
    description: 'Generous 3.0m x 2.4m hand-tufted organic wool rug with geometric carved high-low pile border.',
    dimensions: { width: 3.0, depth: 2.4, height: 0.03 },
    defaultColor: '#ece7df',
    secondaryColor: '#b8afa0',
    colorOptions: ['#ece7df', '#d4cebe', '#737a85', '#333b47', '#9e624c'],
    price: 850,
  },

  // --- BEDROOM ---
  {
    id: 'king-upholstered-bed',
    modelType: 'king-upholstered-bed',
    name: 'King Upholstered Wingback Bed',
    category: 'bedroom',
    description: 'Grand King-size bed with channel-tufted headboard, folded linen duvet, and layered accent pillows.',
    dimensions: { width: 2.05, depth: 2.2, height: 1.2 },
    defaultColor: '#ded8cf',
    secondaryColor: '#8a7765',
    colorOptions: ['#ded8cf', '#3b434e', '#546355', '#48392b', '#b3826d'],
    price: 2600,
  },
  {
    id: 'queen-platform-bed',
    modelType: 'queen-platform-bed',
    name: 'Japandi Low Platform Bed',
    category: 'bedroom',
    description: 'Zen-inspired solid oak low platform bed frame with integrated side ledges and crisp white linen.',
    dimensions: { width: 1.85, depth: 2.15, height: 0.75 },
    defaultColor: '#cca87c', // Natural oak
    secondaryColor: '#f9fafb', // White linen
    colorOptions: ['#cca87c', '#533c2a', '#222222', '#e8dfd3'],
    price: 1950,
  },
  {
    id: 'nightstand-lamp',
    modelType: 'nightstand-lamp',
    name: 'Bedside Nightstand & Glowing Lamp',
    category: 'bedroom',
    description: 'Floating-look bedside cabinet with soft-close drawer and minimalist ceramic globe reading lamp.',
    dimensions: { width: 0.55, depth: 0.42, height: 0.78 },
    defaultColor: '#a88968',
    secondaryColor: '#fff8eb',
    colorOptions: ['#a88968', '#423023', '#25292e', '#e5e7eb'],
    price: 430,
  },
  {
    id: 'modern-wardrobe',
    modelType: 'modern-wardrobe',
    name: 'Minimalist 3-Door Wardrobe',
    category: 'bedroom',
    description: 'Full-height wardrobe with sleek recessed vertical handles and matte lacquer finish.',
    dimensions: { width: 1.6, depth: 0.62, height: 2.25 },
    defaultColor: '#e5e2dc',
    secondaryColor: '#302820',
    colorOptions: ['#e5e2dc', '#33383f', '#7d6148', '#f8fafc'],
    price: 1850,
  },
  {
    id: 'vanity-mirror',
    modelType: 'vanity-mirror',
    name: 'Dressing Vanity Table & Halo Mirror',
    category: 'bedroom',
    description: 'Slim dressing table with brass drawer hardware, round backlit LED mirror, and velvet stool.',
    dimensions: { width: 1.1, depth: 0.48, height: 1.45 },
    defaultColor: '#f3efe8',
    secondaryColor: '#c5a059',
    colorOptions: ['#f3efe8', '#382f28', '#26282c'],
    price: 1100,
  },

  // --- DINING & KITCHEN ---
  {
    id: 'dining-table-wishbone',
    modelType: 'dining-table-wishbone',
    name: 'Solid Timber Dining Set & Chairs',
    category: 'dining',
    description: '6-person oval live-edge timber dining table paired with iconic woven cord Wishbone chairs.',
    dimensions: { width: 2.2, depth: 1.1, height: 0.76 },
    defaultColor: '#bfa07e', // Natural Ash / Oak
    secondaryColor: '#2b231d',
    colorOptions: ['#bfa07e', '#4a3525', '#1e2022', '#dfd3c3'],
    price: 2900,
  },
  {
    id: 'kitchen-island-stools',
    modelType: 'kitchen-island-stools',
    name: 'Waterfall Marble Island & Barstools',
    category: 'dining',
    description: 'Architectural kitchen island with continuous waterfall marble slab, prep sink, and counter barstools.',
    dimensions: { width: 2.4, depth: 1.0, height: 0.92 },
    defaultColor: '#f1f4f6', // Carrara Marble
    secondaryColor: '#362b24', // Stool frames
    colorOptions: ['#f1f4f6', '#2b2f33', '#dfd5c6'],
    price: 3800,
  },
  {
    id: 'sink-cabinet',
    modelType: 'sink-cabinet',
    name: 'Modular Base Sink & Counter Unit',
    category: 'dining',
    description: 'Sleek kitchen base cabinetry with integrated undermount stainless sink and tall arch gooseneck faucet.',
    dimensions: { width: 1.6, depth: 0.65, height: 0.9 },
    defaultColor: '#3d444d', // Charcoal Grey
    secondaryColor: '#cbd5e1', // Stainless sink
    colorOptions: ['#3d444d', '#e2dacf', '#1f2937', '#ffffff'],
    price: 1450,
  },
  {
    id: 'refrigerator-french',
    modelType: 'refrigerator-french',
    name: 'French-Door Stainless Refrigerator',
    category: 'dining',
    description: 'Premium counter-depth refrigerator with double French doors, lower freezer drawer, and brushed finish.',
    dimensions: { width: 0.95, depth: 0.75, height: 1.85 },
    defaultColor: '#9ca3af', // Brushed Steel
    secondaryColor: '#1f2937',
    colorOptions: ['#9ca3af', '#2a2e33', '#ffffff'],
    price: 2400,
  },

  // --- OFFICE & STUDY ---
  {
    id: 'executive-desk-laptop',
    modelType: 'executive-desk-laptop',
    name: 'Executive Timber Desk with Laptop',
    category: 'office',
    description: 'Curved wood executive workspace with leather blotter pad, aluminum slim laptop, and cable raceway.',
    dimensions: { width: 1.7, depth: 0.8, height: 0.75 },
    defaultColor: '#5a3d28', // Dark Walnut
    secondaryColor: '#d1d5db', // Laptop
    colorOptions: ['#5a3d28', '#be9f7b', '#26292e', '#e4ded4'],
    price: 1550,
  },
  {
    id: 'swivel-chair-mesh',
    modelType: 'swivel-chair-mesh',
    name: 'Ergonomic Task Swivel Chair',
    category: 'office',
    description: 'Adjustable ergonomic office chair with breathable mesh backing, lumbar support, and 5-star castor base.',
    dimensions: { width: 0.68, depth: 0.68, height: 1.05 },
    defaultColor: '#1f2937',
    secondaryColor: '#9ca3af',
    colorOptions: ['#1f2937', '#4b5563', '#9ca3af', '#2563eb'],
    price: 680,
  },
  {
    id: 'low-credenza',
    modelType: 'low-credenza',
    name: 'Office Storage Credenza',
    category: 'office',
    description: 'Low-profile locking file and equipment cabinet with warm wooden carcass and matte doors.',
    dimensions: { width: 1.5, depth: 0.45, height: 0.68 },
    defaultColor: '#75583f',
    secondaryColor: '#e5e7eb',
    colorOptions: ['#75583f', '#c9ab8b', '#272d36'],
    price: 880,
  },

  // --- DECOR & ARCHITECTURAL ---
  {
    id: 'potted-monstera',
    modelType: 'potted-monstera',
    name: 'Potted Monstera Deliciosa',
    category: 'decor',
    description: 'Lush Swiss cheese plant with vibrant split leaves housed in a ribbed ceramic planter.',
    dimensions: { width: 0.75, depth: 0.75, height: 1.15 },
    defaultColor: '#2d6a4f', // Foliage green
    secondaryColor: '#f3ede2', // Ceramic pot
    colorOptions: ['#2d6a4f', '#1b4332', '#40916c'],
    price: 240,
  },
  {
    id: 'fiddle-leaf-fig',
    modelType: 'fiddle-leaf-fig',
    name: 'Fiddle Leaf Fig Tree',
    category: 'decor',
    description: 'Tall statement indoor tree with large violin-shaped leaves in a woven artisan seagrass basket.',
    dimensions: { width: 0.85, depth: 0.85, height: 1.85 },
    defaultColor: '#24563b',
    secondaryColor: '#c2a177', // Woven basket
    colorOptions: ['#24563b', '#1b3e2b'],
    price: 390,
  },
  {
    id: 'abstract-gallery-canvas',
    modelType: 'abstract-gallery-canvas',
    name: 'Framed Abstract Gallery Canvas',
    category: 'decor',
    description: 'Large textured modern artwork with subtle earth tones encased in a natural oak float frame.',
    dimensions: { width: 1.4, depth: 0.08, height: 1.0 },
    defaultColor: '#d6c8b4',
    secondaryColor: '#8a6845', // Wood frame
    colorOptions: ['#d6c8b4', '#475569', '#9f5b45', '#334155'],
    price: 520,
    isWallMounted: true,
    elevationOffset: 1.4,
  },
  {
    id: 'halo-ring-chandelier',
    modelType: 'halo-ring-chandelier',
    name: 'Floating Brass Halo Ring Chandelier',
    category: 'decor',
    description: 'Suspended dual concentric LED circular rings with brushed brass finish casting warm ambient illumination.',
    dimensions: { width: 0.95, depth: 0.95, height: 0.65 },
    defaultColor: '#c5a059', // Brass
    secondaryColor: '#fff9e6', // Warm light
    colorOptions: ['#c5a059', '#1f2937', '#e5e7eb'],
    price: 980,
    isCeilingMounted: true,
    elevationOffset: 2.2,
  },
  {
    id: 'soaking-bathtub',
    modelType: 'soaking-bathtub',
    name: 'Freestanding Oval Soaking Tub',
    category: 'decor',
    description: 'Sculptural stone composite oval soaking bathtub accompanied by a floor-mounted chrome filler.',
    dimensions: { width: 1.7, depth: 0.85, height: 0.6 },
    defaultColor: '#fafafa',
    secondaryColor: '#94a3b8',
    colorOptions: ['#fafafa', '#1e293b', '#f1f5f9'],
    price: 3200,
  },
  {
    id: 'picture-window',
    modelType: 'picture-window',
    name: 'Black Steel Architectural Picture Window',
    category: 'decor',
    description: 'Floor-to-ceiling grid picture window offering panoramic outdoor views and natural daylight penetration.',
    dimensions: { width: 2.2, depth: 0.15, height: 2.2 },
    defaultColor: '#18181b', // Black frame
    secondaryColor: '#a5f3fc', // Glass
    colorOptions: ['#18181b', '#f8fafc', '#78716c'],
    price: 1800,
    isWallMounted: true,
    elevationOffset: 0.15,
  },
  {
    id: 'casement-window',
    modelType: 'casement-window',
    name: 'French Casement Divided Window',
    category: 'architectural',
    description: 'Double casement architectural window with operable dual sashes, central divided mullions, and brass latches.',
    dimensions: { width: 1.6, depth: 0.14, height: 1.4 },
    defaultColor: '#1e293b',
    secondaryColor: '#f1f5f9',
    colorOptions: ['#1e293b', '#f8fafc', '#78716c', '#475569'],
    price: 1450,
    isWallMounted: true,
    elevationOffset: 0.5,
  },
  {
    id: 'panoramic-glass-window',
    modelType: 'panoramic-glass-window',
    name: 'Floor-to-Ceiling Panoramic Glass Window',
    category: 'architectural',
    description: 'Monumental architectural glazing system with ultra-slim anodized framing and expansive outdoor landscape horizon.',
    dimensions: { width: 3.6, depth: 0.12, height: 2.6 },
    defaultColor: '#0f172a',
    secondaryColor: '#94a3b8',
    colorOptions: ['#0f172a', '#e2e8f0', '#b45309'],
    price: 3400,
    isWallMounted: true,
    elevationOffset: 0.0,
  },
  {
    id: 'arched-window',
    modelType: 'arched-window',
    name: 'Classic Palladian Arched Window',
    category: 'architectural',
    description: 'Dramatic architectural arched window with sunburst fanlight radial mullions and divided lower glazing.',
    dimensions: { width: 1.4, depth: 0.12, height: 2.2 },
    defaultColor: '#f8fafc',
    secondaryColor: '#334155',
    colorOptions: ['#f8fafc', '#1e293b', '#854d0e'],
    price: 2100,
    isWallMounted: true,
    elevationOffset: 0.2,
  },
  {
    id: 'clerestory-window',
    modelType: 'clerestory-window',
    name: 'Clerestory Transom High Ribbon Window',
    category: 'architectural',
    description: 'High-elevation horizontal architectural ribbon window for natural ambient daylight while preserving wall privacy.',
    dimensions: { width: 3.0, depth: 0.1, height: 0.65 },
    defaultColor: '#1e293b',
    secondaryColor: '#cbd5e1',
    colorOptions: ['#1e293b', '#f8fafc'],
    price: 1200,
    isWallMounted: true,
    elevationOffset: 1.8,
  },
  {
    id: 'interior-door',
    modelType: 'interior-door',
    name: 'Modern Paneled Interior Door',
    category: 'architectural',
    description: 'Architectural flush interior door with door jamb, casing molding, and satin brass lever handle.',
    dimensions: { width: 0.95, depth: 0.12, height: 2.15 },
    defaultColor: '#f8fafc',
    secondaryColor: '#c5a059', // Brass handle
    colorOptions: ['#f8fafc', '#2c2d30', '#8b6e4e'],
    price: 750,
    isWallMounted: true,
    elevationOffset: 0.0,
  },
  {
    id: 'french-double-door',
    modelType: 'french-double-door',
    name: 'Double French Glass Doors',
    category: 'architectural',
    description: 'Pair of elegant divided glass French doors with full casing, meeting stiles, and dual architectural lever handles.',
    dimensions: { width: 1.8, depth: 0.12, height: 2.2 },
    defaultColor: '#f8fafc',
    secondaryColor: '#d4af37',
    colorOptions: ['#f8fafc', '#18181b', '#3b2f2f'],
    price: 1850,
    isWallMounted: true,
    elevationOffset: 0.0,
  },
  {
    id: 'sliding-barn-door',
    modelType: 'sliding-barn-door',
    name: 'Modern Sliding Barn Door & Track',
    category: 'architectural',
    description: 'Overhead exposed matte black steel roller track with heavy timber slab door and recessed flush handle.',
    dimensions: { width: 1.1, depth: 0.15, height: 2.2 },
    defaultColor: '#8c6d48',
    secondaryColor: '#18181b',
    colorOptions: ['#8c6d48', '#f8fafc', '#2c2d30'],
    price: 1100,
    isWallMounted: true,
    elevationOffset: 0.0,
  },
  {
    id: 'pivot-door',
    modelType: 'pivot-door',
    name: 'Grand Architectural Pivot Door',
    category: 'architectural',
    description: 'Oversized contemporary pivot entrance door with off-center axis hinge and full-height architectural pull bar.',
    dimensions: { width: 1.4, depth: 0.16, height: 2.4 },
    defaultColor: '#2b2621',
    secondaryColor: '#d4af37',
    colorOptions: ['#2b2621', '#f8fafc', '#18181b'],
    price: 2600,
    isWallMounted: true,
    elevationOffset: 0.0,
  },
  {
    id: 'fluted-wood-divider',
    modelType: 'fluted-wood-divider',
    name: 'Fluted Timber Room Divider Screen',
    category: 'architectural',
    description: 'Vertical oak slat architectural partition screen creating semi-private spatial zoning with filtered light.',
    dimensions: { width: 1.6, depth: 0.12, height: 2.6 },
    defaultColor: '#b89063',
    secondaryColor: '#3a2e25',
    colorOptions: ['#b89063', '#2c241d', '#f1ede6'],
    price: 1250,
    elevationOffset: 0.0,
  },
  {
    id: 'glass-steel-partition',
    modelType: 'glass-steel-partition',
    name: 'Industrial Glass & Steel Partition Wall',
    category: 'architectural',
    description: 'Loft-style black steel grid partition wall with acoustic laminated clear glass panels.',
    dimensions: { width: 2.4, depth: 0.1, height: 2.6 },
    defaultColor: '#18181b',
    secondaryColor: '#94a3b8',
    colorOptions: ['#18181b', '#ffffff', '#78716c'],
    price: 2200,
    elevationOffset: 0.0,
  },
  {
    id: 'pony-wall',
    modelType: 'pony-wall',
    name: 'Architectural Half-Height Pony Wall',
    category: 'architectural',
    description: 'Low-profile half-height architectural dividing wall capped with solid white oak ledge.',
    dimensions: { width: 2.0, depth: 0.2, height: 1.1 },
    defaultColor: '#f1f5f9',
    secondaryColor: '#b89063',
    colorOptions: ['#f1f5f9', '#ffffff', '#334155'],
    price: 650,
    elevationOffset: 0.0,
  },
  {
    id: 'drywall-partition',
    modelType: 'drywall-partition',
    name: 'Interior Drywall Partition Wall',
    category: 'architectural',
    description: 'Full-height interior stud drywall partition with baseboard trim for spatial zoning.',
    dimensions: { width: 2.0, depth: 0.12, height: 2.6 },
    defaultColor: '#f8fafc',
    secondaryColor: '#e2e8f0',
    colorOptions: ['#f8fafc', '#f1f5f9', '#334155', '#3d4b41'],
    price: 450,
    elevationOffset: 0.0,
  },
  {
    id: 'modern-linear-fireplace',
    modelType: 'modern-linear-fireplace',
    name: 'Modern Recessed Linear Fireplace',
    category: 'architectural',
    description: 'Contemporary recessed ribbon fireplace with floating timber mantle, dark hearth cavity, and glowing embers.',
    dimensions: { width: 2.2, depth: 0.38, height: 1.2 },
    defaultColor: '#f8fafc',
    secondaryColor: '#3d2817',
    colorOptions: ['#f8fafc', '#18181b', '#e2e8f0'],
    price: 2900,
    elevationOffset: 0.0,
  },
  {
    id: 'architectural-pillar',
    modelType: 'architectural-pillar',
    name: 'Architectural Structural Column',
    category: 'architectural',
    description: 'Classical round structural column with molded square plinth base and crown capital.',
    dimensions: { width: 0.35, depth: 0.35, height: 2.8 },
    defaultColor: '#f8fafc',
    secondaryColor: '#e2e8f0',
    colorOptions: ['#f8fafc', '#1e293b', '#cbd5e1'],
    price: 480,
    elevationOffset: 0.0,
  },
  {
    id: 'custom-masonry-wall',
    modelType: 'custom-masonry-wall',
    name: 'Custom Architectural Wall (Sizable)',
    category: 'architectural',
    description: 'Fully customizable masonry/partition wall. Freely adjust length, thickness (e.g. 150mm, 200mm, 230mm / 9"), and height (up to 19ft).',
    dimensions: { width: 3.0, depth: 0.23, height: 5.79 },
    defaultColor: '#f1f5f9',
    secondaryColor: '#cbd5e1',
    colorOptions: ['#f1f5f9', '#ffffff', '#e2e8f0', '#0d4a36', '#334155'],
    price: 320,
    elevationOffset: 0.0,
  },
  {
    id: 'architectural-ceiling-beam',
    modelType: 'architectural-ceiling-beam',
    name: 'Exposed Timber Ceiling Beam',
    category: 'architectural',
    description: 'Solid rustic white oak exposed structural ceiling beam running across the upper room envelope.',
    dimensions: { width: 6.0, depth: 0.24, height: 0.2 },
    defaultColor: '#453224',
    secondaryColor: '#261b13',
    colorOptions: ['#453224', '#f1f5f9', '#1a140f'],
    price: 520,
    isCeilingMounted: true,
    elevationOffset: 2.7,
  },
  {
    id: 'structural-beam-concrete',
    modelType: 'structural-beam-concrete',
    name: 'Reinforced Concrete Beam (B1, B2...)',
    category: 'architectural',
    description: 'Structural framing beam (300mm × 600mm) connecting columns with high-strength concrete and chamfered edges.',
    dimensions: { width: 6.0, depth: 0.30, height: 0.60 },
    defaultColor: '#94a3b8',
    secondaryColor: '#64748b',
    colorOptions: ['#94a3b8', '#64748b', '#cbd5e1'],
    price: 650,
    isCeilingMounted: true,
    elevationOffset: 3.5,
  },
  {
    id: 'structural-beam-steel',
    modelType: 'structural-beam-steel',
    name: 'Wide-Flange Steel Beam (B1, B2...)',
    category: 'architectural',
    description: 'AISC wide-flange structural steel I-beam with bolted end plates and matte protective primer finish.',
    dimensions: { width: 6.0, depth: 0.25, height: 0.45 },
    defaultColor: '#334155',
    secondaryColor: '#1e293b',
    colorOptions: ['#334155', '#475569', '#0f172a'],
    price: 850,
    isCeilingMounted: true,
    elevationOffset: 3.5,
  },
  {
    id: 'structural-column-square',
    modelType: 'structural-column-square',
    name: 'Structural Concrete Column (C1, C2...)',
    category: 'architectural',
    description: 'Square reinforced concrete structural column (450mm × 450mm) with molded plinth base and header capital.',
    dimensions: { width: 0.45, depth: 0.45, height: 3.5 },
    defaultColor: '#94a3b8',
    secondaryColor: '#64748b',
    colorOptions: ['#94a3b8', '#64748b', '#cbd5e1'],
    price: 750,
  },
  {
    id: 'structural-column-steel',
    modelType: 'structural-column-steel',
    name: 'Wide-Flange Steel Column (C1, C2...)',
    category: 'architectural',
    description: 'Heavy structural steel H-column with 4-bolt base plate and capital flange seat for office framing.',
    dimensions: { width: 0.35, depth: 0.35, height: 3.5 },
    defaultColor: '#334155',
    secondaryColor: '#1e293b',
    colorOptions: ['#334155', '#475569', '#1e293b'],
    price: 920,
  },

  // --- MASJID & ISLAMIC ARCHITECTURE ---
  {
    id: 'masjid-qibla-facade',
    modelType: 'masjid-qibla-facade',
    name: 'Imperial Monumental Qibla Wall Facade',
    category: 'masjid',
    description: 'Breathtaking 8-meter architectural Qibla wall feature with tiered horseshoe arch, Moroccan Zellij star tile inlays, continuous Quranic calligraphy frieze, Allah/Muhammad medallions, and warm cove lighting.',
    dimensions: { width: 8.0, depth: 0.45, height: 5.2 },
    defaultColor: '#f8f8f6',
    secondaryColor: '#d4af37',
    colorOptions: ['#f8f8f6', '#0e4a36', '#2b1810'],
    price: 14500,
  },
  {
    id: 'masjid-mehrab-niche',
    modelType: 'masjid-mehrab-niche',
    name: 'Grand Marble Mihrab Arch Niche',
    category: 'masjid',
    description: 'Majestic Islamic pointed horseshoe arch with dual marble columns, muqarnas capitals, Quranic calligraphy band, and hanging sanctuary lamp.',
    dimensions: { width: 4.8, depth: 1.8, height: 4.5 },
    defaultColor: '#f8f8f6',
    secondaryColor: '#d4af37',
    colorOptions: ['#f8f8f6', '#0e4a36', '#3b2314'],
    price: 8500,
  },
  {
    id: 'masjid-minbar',
    modelType: 'masjid-minbar',
    name: 'Carved Hardwood Stepped Minbar',
    category: 'masjid',
    description: 'Traditional Islamic stepped wooden pulpit with 5 ascending brass-nosed steps, Mashrabiya lattice railings, and arched dome canopy.',
    dimensions: { width: 1.1, depth: 2.2, height: 3.4 },
    defaultColor: '#4a2c16',
    secondaryColor: '#d4af37',
    colorOptions: ['#4a2c16', '#2b1810', '#6b4226'],
    price: 6200,
  },
  {
    id: 'masjid-chandelier',
    modelType: 'masjid-chandelier',
    name: 'Ottoman Crystal Ring Chandelier',
    category: 'masjid',
    description: 'Grand 3-ring mosque brass chandelier with concentric Arabesque rings, crystal prism pendants, and warm perimeter glowing lanterns.',
    dimensions: { width: 3.2, depth: 3.2, height: 2.4 },
    defaultColor: '#d4af37',
    secondaryColor: '#ffffff',
    colorOptions: ['#d4af37', '#bfa15f', '#1c1917'],
    price: 7800,
    isCeilingMounted: true,
    elevationOffset: 3.6,
  },
  {
    id: 'masjid-quran-rihal',
    modelType: 'masjid-quran-rihal',
    name: 'Carved Walnut Folding Rihal & Quran',
    category: 'masjid',
    description: 'Hand-carved folding X-frame walnut bookstand with mother-of-pearl inlay, open holy Quran, and green satin bookmark ribbon.',
    dimensions: { width: 0.6, depth: 0.5, height: 0.45 },
    defaultColor: '#3d2314',
    secondaryColor: '#fbf8ee',
    colorOptions: ['#3d2314', '#1f1610', '#5a3d28'],
    price: 320,
  },
  {
    id: 'masjid-quran-shelf',
    modelType: 'masjid-quran-shelf',
    name: 'Mosque Perimeter Quran Bookcase',
    category: 'masjid',
    description: 'Low-profile solid walnut 3-tier perimeter bookcase containing gold-embossed holy Quran volumes.',
    dimensions: { width: 2.0, depth: 0.35, height: 1.2 },
    defaultColor: '#422617',
    secondaryColor: '#14532d',
    colorOptions: ['#422617', '#2a180f', '#5e3820'],
    price: 850,
  },
  {
    id: 'masjid-calligraphy-wall',
    modelType: 'masjid-calligraphy-wall',
    name: 'Gilded Relief Calligraphy Medallion',
    category: 'masjid',
    description: 'Circular wall medallion with 24K gilded Arabic calligraphy relief on deep emerald background.',
    dimensions: { width: 1.2, depth: 0.08, height: 1.2 },
    defaultColor: '#d4af37',
    secondaryColor: '#064e3b',
    colorOptions: ['#d4af37', '#064e3b', '#7f1d1d'],
    price: 1100,
    elevationOffset: 2.4,
  },
  {
    id: 'masjid-mashrabiya',
    modelType: 'masjid-mashrabiya',
    name: 'Mashrabiya Geometric Lattice Screen',
    category: 'masjid',
    description: 'Authentic Islamic carved wooden Jali lattice partition screen for modesty divisions or entrance foyer.',
    dimensions: { width: 1.6, depth: 0.12, height: 2.2 },
    defaultColor: '#3b2314',
    secondaryColor: '#d4af37',
    colorOptions: ['#3b2314', '#1a110b', '#603813'],
    price: 1450,
  },
  {
    id: 'masjid-adhan-clock',
    modelType: 'masjid-adhan-clock',
    name: 'Digital Mosque Adhan Schedule Clock',
    category: 'masjid',
    description: 'Wall-mounted LED digital prayer timetable showing Fajr, Dhuhr, Asr, Maghrib, and Isha with gilded brass border.',
    dimensions: { width: 0.95, depth: 0.06, height: 0.65 },
    defaultColor: '#1a1a1a',
    secondaryColor: '#22c55e',
    colorOptions: ['#1a1a1a', '#d4af37'],
    price: 490,
    elevationOffset: 2.0,
  },
  {
    id: 'masjid-shoe-rack',
    modelType: 'masjid-shoe-rack',
    name: 'Foyer Shoe Cubby Unit (15 Slots)',
    category: 'masjid',
    description: 'Multi-compartment solid hardwood shoe storage unit for mosque entrance foyer.',
    dimensions: { width: 2.0, depth: 0.45, height: 1.1 },
    defaultColor: '#4a3321',
    secondaryColor: '#362416',
    colorOptions: ['#4a3321', '#2c1e14', '#66462d'],
    price: 680,
  },
  {
    id: 'masjid-pillar',
    modelType: 'masjid-pillar',
    name: 'Monumental Octagonal Mosque Pillar',
    category: 'masjid',
    description: 'Fluted marble octagonal column with carved muqarnas capital and square plinth base.',
    dimensions: { width: 0.75, depth: 0.75, height: 4.8 },
    defaultColor: '#f5f3ee',
    secondaryColor: '#d4af37',
    colorOptions: ['#f5f3ee', '#e5e0d8', '#ffffff'],
    price: 1950,
  },
  {
    id: 'masjid-carpet-runner',
    modelType: 'masjid-carpet-runner',
    name: 'Saff Row Prayer Mat Runner',
    category: 'masjid',
    description: 'Individual emerald velvet prayer rug runner with gold Mihrab arch and alignment border.',
    dimensions: { width: 0.8, depth: 1.25, height: 0.02 },
    defaultColor: '#0f4c3a',
    secondaryColor: '#d4af37',
    colorOptions: ['#0f4c3a', '#7a1420', '#ded5c5'],
    price: 180,
  },
];
