import { DesignTemplate } from '../types';

export const DESIGNER_TEMPLATES: DesignTemplate[] = [
  {
    id: 'masjid-grand-musalla',
    name: 'Grand Islamic Masjid Musalla',
    category: 'Masjid',
    description: 'Authentic Islamic mosque floor plan with 40.9\' Qibla wall, 18\' × 7\' protruding Mehrab niche, carved Minbar, Turkish emerald carpet, and prayer Saff rows (~310 worshippers).',
    roomConfig: {
      width: 19.3, // ~63.2'
      length: 22.4, // ~73.5'
      height: 4.8, // 16'
      flooring: 'mosque-carpet-emerald',
      baseWallColor: '#faf8f5',
      baseboardColor: '#d6cfbe',
      accentWalls: {
        north: { enabled: true, color: '#0d4a36', finish: 'flat' }, // Qibla Wall Accent
        south: { enabled: false, color: '#faf8f5', finish: 'flat' },
        east: { enabled: false, color: '#faf8f5', finish: 'flat' },
        west: { enabled: false, color: '#faf8f5', finish: 'flat' },
      },
      wallVisibility: {
        north: true,
        south: true,
        east: true,
        west: true,
        extension: true,
      },
      wallThicknessMeters: 0.23, // 230mm (9" standard masonry)
      wallHeightMeters: 5.761, // 5761 mm (matching outer column & beam resting level)
      showCeiling: false,
      gridSnap: true,
      gridSnapSize: 0.3048,
      unitSystem: 'imperial',
      masjidConfig: {
        isMasjid: true,
        qiblaWallFeet: 40.9,
        leftWallFeet: 73.5,
        rightWallFeet: 69.1,
        backWallFeet: 63.2,
        mehrabWidthFeet: 18.0,
        mehrabDepthFeet: 7.0,
        mehrabHeightFeet: 9.0,
        showSaffLines: true,
        saffSpacingMeters: 1.2,
        saffColor: '#d4af37',
        estimatedCapacity: 340,
        showStructuralGrid: true,
        showColumns: true,
        removeCenterColumns: true, // Center columns removed; clear span hall
        showTieBeams: true,
        showMainBeams: true,
        mainColumnWidthMm: 650,
        mainColumnDepthMm: 900,
        mainColumnCount: 12, // 12 outer perimeter columns
        tieBeamHeightFt: 13,
        tieBeamWidthMm: 150,
        tieBeamHeightMm: 450,
        mainBeamHeightFt: 18.9,
        mainBeamElevationMm: 5761, // 5761 mm from ground level
        mainBeamWidthMm: 450, // 450 mm width
        mainBeamDepthMm: 900, // 900 mm height
        hasGateColumns: true, // Two columns on main gate/door (450mm x 450mm)
        gatePosition: 'diagonal-corner', // Main gate diagonal in the inner making a triangular shape 6 ft deeper
        isDiagonalGate: true,
        gateDepthFeet: 6, // 6 feet deeper from boundary wall
        hasExtraGateRightColumn: false, // Column in front of main door removed per user request
        extraGateRightColumnWidthMm: 450,
        extraGateRightColumnDepthMm: 450,
        hasUmbrellaCornerCanopy: true, // Door columns go up and meet at corner in umbrella shape
        umbrellaRakingBeamWidthMm: 350,
        umbrellaRakingBeamDepthMm: 450,
        gateWidthFeet: 12,
        gateColumnWidthMm: 450,
        gateColumnDepthMm: 450,
        hasQiblaColumns: true, // Two columns on Qibla wall (450mm x 450mm)
        hasQiblaCenterColumn: true,
        qiblaColumnWidthMm: 450,
        qiblaColumnDepthMm: 450,
        qiblaCenterColumnWidthMm: 450,
        qiblaCenterColumnDepthMm: 450,
        columnSpacingFeet: 20, // 20 feet (6.096 m) between both center column lines
        hasTwoLongitudinalBeams: true, // Two longitudinal beams (450x900mm) resting on door & qibla columns, 20 ft apart
        hasCentralSpineBeam: true,
        longitudinalBeamWidthMm: 450,
        longitudinalBeamDepthMm: 900,
        centralSpineBeamWidthMm: 450,
        centralSpineBeamDepthMm: 900,
        extensionFeet: 8.0,
        extensionColumnCount: 2, // outer extension columns
        extensionColumnWidthMm: 150,
        extensionColumnDepthMm: 200,
        traditionalIslamicWalls: true,
        islamicWallStyle: 'andalusian-moroccan',
        showPerimeterCalligraphyFrieze: true,
        showPerimeterArchedBays: true,
        showPerimeterZelligeWainscot: true,
        showPerimeterQuranAlcoves: true,
        showPerimeterMishkatLamps: true,
        showPrayerTimeBoard: true,
        showShoeStorageAlcoves: true,
      },
    },
    items: [
      {
        modelType: 'masjid-mehrab-niche',
        name: 'Grand Marble Mihrab Arch Niche',
        category: 'masjid',
        position: [0, 0, -12.4],
        rotationY: 0,
        dimensions: { width: 4.8, depth: 1.8, height: 4.5 },
        color: '#f8f8f6',
        secondaryColor: '#d4af37',
        price: 8500,
      },
      {
        modelType: 'masjid-minbar',
        name: 'Carved Hardwood Stepped Minbar',
        category: 'masjid',
        position: [3.4, 0, -10.2],
        rotationY: 0,
        dimensions: { width: 1.1, depth: 2.2, height: 3.4 },
        color: '#4a2c16',
        secondaryColor: '#d4af37',
        price: 6200,
      },
      {
        modelType: 'masjid-quran-rihal',
        name: 'Carved Walnut Folding Rihal & Quran',
        category: 'masjid',
        position: [0, 0, -11.4],
        rotationY: 0,
        dimensions: { width: 0.6, depth: 0.5, height: 0.45 },
        color: '#3d2314',
        secondaryColor: '#fbf8ee',
        price: 320,
      },
      {
        modelType: 'masjid-chandelier',
        name: 'Ottoman Crystal Ring Chandelier',
        category: 'masjid',
        position: [0, 3.6, 0],
        rotationY: 0,
        dimensions: { width: 3.2, depth: 3.2, height: 2.4 },
        color: '#d4af37',
        secondaryColor: '#ffffff',
        price: 7800,
      },
      {
        modelType: 'masjid-calligraphy-wall',
        name: 'Gilded Relief Calligraphy Medallion (Left)',
        category: 'masjid',
        position: [-4.6, 2.4, -10.85],
        rotationY: 0,
        dimensions: { width: 1.2, depth: 0.08, height: 1.2 },
        color: '#d4af37',
        secondaryColor: '#064e3b',
        price: 1100,
      },
      {
        modelType: 'masjid-adhan-clock',
        name: 'Digital Mosque Adhan Schedule Clock',
        category: 'masjid',
        position: [4.8, 2.0, -10.85],
        rotationY: 0,
        dimensions: { width: 0.95, depth: 0.06, height: 0.65 },
        color: '#1a1a1a',
        secondaryColor: '#22c55e',
        price: 490,
      },
      {
        modelType: 'masjid-quran-shelf',
        name: 'Mosque Perimeter Quran Bookcase (West Wall)',
        category: 'masjid',
        position: [-7.8, 0, 1.0],
        rotationY: 90,
        dimensions: { width: 2.0, depth: 0.35, height: 1.2 },
        color: '#422617',
        secondaryColor: '#14532d',
        price: 850,
      },
      {
        modelType: 'masjid-quran-shelf',
        name: 'Mosque Perimeter Quran Bookcase (East Wall)',
        category: 'masjid',
        position: [7.8, 0, 1.0],
        rotationY: -90,
        dimensions: { width: 2.0, depth: 0.35, height: 1.2 },
        color: '#422617',
        secondaryColor: '#14532d',
        price: 850,
      },
      {
        modelType: 'masjid-shoe-rack',
        name: 'Entrance Shoe Storage (Left)',
        category: 'masjid',
        position: [-4.0, 0, 10.2],
        rotationY: 180,
        dimensions: { width: 2.0, depth: 0.45, height: 1.1 },
        color: '#4a3321',
        secondaryColor: '#362416',
        price: 680,
      },
      {
        modelType: 'masjid-shoe-rack',
        name: 'Entrance Shoe Storage (Right)',
        category: 'masjid',
        position: [4.0, 0, 10.2],
        rotationY: 180,
        dimensions: { width: 2.0, depth: 0.45, height: 1.1 },
        color: '#4a3321',
        secondaryColor: '#362416',
        price: 680,
      },
    ],
  },
  {
    id: 'nordic-living',
    name: 'Nordic Sunlit Living Space',
    category: 'Living',
    description: 'An airy Scandinavian sanctuary combining textured bouclé seating, warm natural oak, and lush greenery.',
    roomConfig: {
      width: 7.0,
      length: 6.0,
      height: 2.8,
      flooring: 'natural-oak',
      baseWallColor: '#f7f6f2',
      baseboardColor: '#ece9e2',
      accentWalls: {
        north: { enabled: true, color: '#3d4b41', finish: 'flat' }, // Muted sage accent
        south: { enabled: false, color: '#f7f6f2', finish: 'flat' },
        east: { enabled: false, color: '#f7f6f2', finish: 'flat' },
        west: { enabled: false, color: '#f7f6f2', finish: 'flat' },
      },
    },
    items: [
      {
        modelType: 'area-rug-woven',
        name: 'Artisan Textured Area Rug',
        category: 'living',
        position: [0, 0, 0.2],
        rotationY: 0,
        dimensions: { width: 3.0, depth: 2.4, height: 0.03 },
        color: '#ece7df',
        secondaryColor: '#b8afa0',
        price: 850,
      },
      {
        modelType: 'sectional-l-sofa',
        name: 'Nordic L-Shape Sectional Sofa',
        category: 'living',
        position: [0, 0, 0.4],
        rotationY: 0,
        dimensions: { width: 2.8, depth: 1.8, height: 0.85 },
        color: '#e5e2dc',
        secondaryColor: '#3a2e25',
        price: 2450,
      },
      {
        modelType: 'coffee-table-minimal',
        name: 'Sculptural Marble Coffee Table',
        category: 'living',
        position: [-0.1, 0, -0.2],
        rotationY: 15,
        dimensions: { width: 1.3, depth: 0.7, height: 0.42 },
        color: '#f1f1ee',
        secondaryColor: '#b89c66',
        price: 920,
      },
      {
        modelType: 'lounge-armchair',
        name: 'Curved Shell Lounge Armchair',
        category: 'living',
        position: [-1.8, 0, 0.1],
        rotationY: 55,
        dimensions: { width: 0.88, depth: 0.85, height: 0.8 },
        color: '#b59a7a',
        secondaryColor: '#1a1a1a',
        price: 790,
      },
      {
        modelType: 'media-credenza-tv',
        name: 'Fluted Media Credenza & OLED TV',
        category: 'living',
        position: [0, 0, -2.6],
        rotationY: 0,
        dimensions: { width: 2.1, depth: 0.45, height: 1.45 },
        color: '#5c4033',
        secondaryColor: '#111827',
        price: 2150,
      },
      {
        modelType: 'arc-floor-lamp',
        name: 'Monumental Brass Arc Floor Lamp',
        category: 'living',
        position: [2.3, 0, 1.8],
        rotationY: -135,
        dimensions: { width: 1.6, depth: 0.45, height: 2.15 },
        color: '#c5a059',
        secondaryColor: '#f3f4f6',
        price: 640,
      },
      {
        modelType: 'potted-monstera',
        name: 'Potted Monstera Deliciosa',
        category: 'decor',
        position: [-2.6, 0, -2.2],
        rotationY: 45,
        dimensions: { width: 0.75, depth: 0.75, height: 1.15 },
        color: '#2d6a4f',
        secondaryColor: '#f3ede2',
        price: 240,
      },
      {
        modelType: 'picture-window',
        name: 'Black Steel Architectural Picture Window',
        category: 'decor',
        position: [-3.4, 0.2, 0],
        rotationY: 90,
        dimensions: { width: 2.2, depth: 0.15, height: 2.2 },
        color: '#18181b',
        secondaryColor: '#a5f3fc',
        price: 1800,
      },
      {
        modelType: 'open-bookshelf',
        name: 'Architectural Open Bookshelf',
        category: 'living',
        position: [2.8, 0, -1.8],
        rotationY: -90,
        dimensions: { width: 1.2, depth: 0.38, height: 2.0 },
        color: '#2b231d',
        secondaryColor: '#1f2937',
        price: 1120,
      },
    ],
  },
  {
    id: 'japandi-bedroom',
    name: 'Japandi Serenity Bedroom',
    category: 'Bedroom',
    description: 'A harmonious blend of Japanese wabi-sabi simplicity and Scandinavian modern functionality.',
    roomConfig: {
      width: 6.5,
      length: 5.5,
      height: 2.8,
      flooring: 'herringbone',
      baseWallColor: '#f3efe8',
      baseboardColor: '#e0d8cc',
      accentWalls: {
        north: { enabled: true, color: '#a67c52', finish: 'wood-slats' }, // Slat acoustic wall
        south: { enabled: false, color: '#f3efe8', finish: 'flat' },
        east: { enabled: false, color: '#f3efe8', finish: 'flat' },
        west: { enabled: false, color: '#f3efe8', finish: 'flat' },
      },
    },
    items: [
      {
        modelType: 'queen-platform-bed',
        name: 'Japandi Low Platform Bed',
        category: 'bedroom',
        position: [0, 0, -1.2],
        rotationY: 0,
        dimensions: { width: 1.85, depth: 2.15, height: 0.75 },
        color: '#cca87c',
        secondaryColor: '#f9fafb',
        price: 1950,
      },
      {
        modelType: 'nightstand-lamp',
        name: 'Bedside Nightstand & Glowing Lamp',
        category: 'bedroom',
        position: [-1.55, 0, -2.0],
        rotationY: 0,
        dimensions: { width: 0.55, depth: 0.42, height: 0.78 },
        color: '#a88968',
        secondaryColor: '#fff8eb',
        price: 430,
      },
      {
        modelType: 'nightstand-lamp',
        name: 'Bedside Nightstand & Glowing Lamp',
        category: 'bedroom',
        position: [1.55, 0, -2.0],
        rotationY: 0,
        dimensions: { width: 0.55, depth: 0.42, height: 0.78 },
        color: '#a88968',
        secondaryColor: '#fff8eb',
        price: 430,
      },
      {
        modelType: 'halo-ring-chandelier',
        name: 'Floating Brass Halo Ring Chandelier',
        category: 'decor',
        position: [0, 2.2, 0],
        rotationY: 0,
        dimensions: { width: 0.95, depth: 0.95, height: 0.65 },
        color: '#c5a059',
        secondaryColor: '#fff9e6',
        price: 980,
      },
      {
        modelType: 'modern-wardrobe',
        name: 'Minimalist 3-Door Wardrobe',
        category: 'bedroom',
        position: [-2.6, 0, 0.8],
        rotationY: 90,
        dimensions: { width: 1.6, depth: 0.62, height: 2.25 },
        color: '#e5e2dc',
        secondaryColor: '#302820',
        price: 1850,
      },
      {
        modelType: 'vanity-mirror',
        name: 'Dressing Vanity Table & Halo Mirror',
        category: 'bedroom',
        position: [2.5, 0, 0.8],
        rotationY: -90,
        dimensions: { width: 1.1, depth: 0.48, height: 1.45 },
        color: '#f3efe8',
        secondaryColor: '#c5a059',
        price: 1100,
      },
      {
        modelType: 'fiddle-leaf-fig',
        name: 'Fiddle Leaf Fig Tree',
        category: 'decor',
        position: [2.4, 0, -2.0],
        rotationY: 30,
        dimensions: { width: 0.85, depth: 0.85, height: 1.85 },
        color: '#24563b',
        secondaryColor: '#c2a177',
        price: 390,
      },
    ],
  },
  {
    id: 'executive-studio',
    name: 'Executive Architectural Studio',
    category: 'Office',
    description: 'A focused, high-productivity home office with ergonomic seating, rich walnut tones, and abundant storage.',
    roomConfig: {
      width: 6.0,
      length: 5.0,
      height: 2.8,
      flooring: 'dark-walnut',
      baseWallColor: '#ecebe8',
      baseboardColor: '#d6d3cc',
      accentWalls: {
        north: { enabled: true, color: '#273444', finish: 'flat' }, // Deep charcoal navy
        south: { enabled: false, color: '#ecebe8', finish: 'flat' },
        east: { enabled: false, color: '#ecebe8', finish: 'flat' },
        west: { enabled: false, color: '#ecebe8', finish: 'flat' },
      },
    },
    items: [
      {
        modelType: 'executive-desk-laptop',
        name: 'Executive Timber Desk with Laptop',
        category: 'office',
        position: [0, 0, -0.3],
        rotationY: 0,
        dimensions: { width: 1.7, depth: 0.8, height: 0.75 },
        color: '#5a3d28',
        secondaryColor: '#d1d5db',
        price: 1550,
      },
      {
        modelType: 'swivel-chair-mesh',
        name: 'Ergonomic Task Swivel Chair',
        category: 'office',
        position: [0, 0, -1.0],
        rotationY: 0,
        dimensions: { width: 0.68, depth: 0.68, height: 1.05 },
        color: '#1f2937',
        secondaryColor: '#9ca3af',
        price: 680,
      },
      {
        modelType: 'low-credenza',
        name: 'Office Storage Credenza',
        category: 'office',
        position: [0, 0, -2.0],
        rotationY: 0,
        dimensions: { width: 1.5, depth: 0.45, height: 0.68 },
        color: '#75583f',
        secondaryColor: '#e5e7eb',
        price: 880,
      },
      {
        modelType: 'open-bookshelf',
        name: 'Architectural Open Bookshelf',
        category: 'living',
        position: [-2.4, 0, 0.4],
        rotationY: 90,
        dimensions: { width: 1.2, depth: 0.38, height: 2.0 },
        color: '#2b231d',
        secondaryColor: '#1f2937',
        price: 1120,
      },
      {
        modelType: 'lounge-armchair',
        name: 'Curved Shell Lounge Armchair',
        category: 'living',
        position: [1.8, 0, 1.2],
        rotationY: -140,
        dimensions: { width: 0.88, depth: 0.85, height: 0.8 },
        color: '#b59a7a',
        secondaryColor: '#1a1a1a',
        price: 790,
      },
      {
        modelType: 'abstract-gallery-canvas',
        name: 'Framed Abstract Gallery Canvas',
        category: 'decor',
        position: [0, 1.4, -2.42],
        rotationY: 0,
        dimensions: { width: 1.4, depth: 0.08, height: 1.0 },
        color: '#d6c8b4',
        secondaryColor: '#8a6845',
        price: 520,
      },
      {
        modelType: 'arc-floor-lamp',
        name: 'Monumental Brass Arc Floor Lamp',
        category: 'living',
        position: [2.2, 0, -1.6],
        rotationY: -110,
        dimensions: { width: 1.6, depth: 0.45, height: 2.15 },
        color: '#c5a059',
        secondaryColor: '#f3f4f6',
        price: 640,
      },
    ],
  },
  {
    id: 'open-kitchen-dining',
    name: 'Open Chef Kitchen & Dining Space',
    category: 'Dining',
    description: 'An expansive open-concept entertaining environment with waterfall marble island and timber dining set.',
    roomConfig: {
      width: 7.5,
      length: 6.5,
      height: 2.9,
      flooring: 'carrara-marble',
      baseWallColor: '#faf8f5',
      baseboardColor: '#e8e5df',
      accentWalls: {
        north: { enabled: true, color: '#2b2f33', finish: 'flat' }, // Contrast dark kitchen wall
        south: { enabled: false, color: '#faf8f5', finish: 'flat' },
        east: { enabled: false, color: '#faf8f5', finish: 'flat' },
        west: { enabled: false, color: '#faf8f5', finish: 'flat' },
      },
    },
    items: [
      {
        modelType: 'kitchen-island-stools',
        name: 'Waterfall Marble Island & Barstools',
        category: 'dining',
        position: [0, 0, -1.2],
        rotationY: 0,
        dimensions: { width: 2.4, depth: 1.0, height: 0.92 },
        color: '#f1f4f6',
        secondaryColor: '#362b24',
        price: 3800,
      },
      {
        modelType: 'sink-cabinet',
        name: 'Modular Base Sink & Counter Unit',
        category: 'dining',
        position: [-1.8, 0, -2.8],
        rotationY: 0,
        dimensions: { width: 1.6, depth: 0.65, height: 0.9 },
        color: '#3d444d',
        secondaryColor: '#cbd5e1',
        price: 1450,
      },
      {
        modelType: 'refrigerator-french',
        name: 'French-Door Stainless Refrigerator',
        category: 'dining',
        position: [2.5, 0, -2.7],
        rotationY: 0,
        dimensions: { width: 0.95, depth: 0.75, height: 1.85 },
        color: '#9ca3af',
        secondaryColor: '#1f2937',
        price: 2400,
      },
      {
        modelType: 'dining-table-wishbone',
        name: 'Solid Timber Dining Set & Chairs',
        category: 'dining',
        position: [0, 0, 1.4],
        rotationY: 0,
        dimensions: { width: 2.2, depth: 1.1, height: 0.76 },
        color: '#bfa07e',
        secondaryColor: '#2b231d',
        price: 2900,
      },
      {
        modelType: 'halo-ring-chandelier',
        name: 'Floating Brass Halo Ring Chandelier',
        category: 'decor',
        position: [0, 2.3, 1.4],
        rotationY: 0,
        dimensions: { width: 0.95, depth: 0.95, height: 0.65 },
        color: '#c5a059',
        secondaryColor: '#fff9e6',
        price: 980,
      },
      {
        modelType: 'fiddle-leaf-fig',
        name: 'Fiddle Leaf Fig Tree',
        category: 'decor',
        position: [3.0, 0, 2.2],
        rotationY: 0,
        dimensions: { width: 0.85, depth: 0.85, height: 1.85 },
        color: '#24563b',
        secondaryColor: '#c2a177',
        price: 390,
      },
    ],
  },
];
